// <auto-generated />
using Bicicleteria.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bicicleteria.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601210816_RenameUsuarioTipoToRol")]
    partial class RenameUsuarioTipoToRol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bicicleteria.Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Montaña",
                            Description = "Bicicleta de montaña de 26 pulgadas con suspensión delantera y frenos de disco.",
                            Name = "Bicicleta Mountain Bike",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Ruta",
                            Description = "Bicicleta de ruta ligera y rápida, ideal para carreteras. Marco de aluminio.",
                            Name = "Bicicleta Ruta",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Urbana",
                            Description = "Bicicleta cómoda y práctica para desplazamientos en ciudad con canasta delantera.",
                            Name = "Bicicleta Urbana",
                            Price = 449.99m
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mail");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numerotelefono");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sistema",
                            Mail = "admin@bicileteria.com",
                            Nombre = "Admin",
                            NumeroTelefono = "+34 900 000 001",
                            PasswordHash = "$2a$11$aDMvxi19.4WXx6ICMLz6I.Y2kSuLiHpUWaTDS3WydVDamXXwwKLMe",
                            Rol = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Vendedor",
                            Mail = "usuario@bicileteria.com",
                            Nombre = "Usuario",
                            NumeroTelefono = "+34 900 000 002",
                            PasswordHash = "$2a$11$RAFttRFyiX2DhbUFGjQo/.OmvG9pK5RQG2pGLMNC8RMYW4GReiTV.",
                            Rol = "vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ejemplo",
                            Mail = "cliente@bicileteria.com",
                            Nombre = "Cliente",
                            NumeroTelefono = "+34 900 000 003",
                            PasswordHash = "$2a$11$xqfICPou/6t.rdfEEaFAYe5Sf2RgTZz5UapBrgJnB.TPzFJxlOjrG",
                            Rol = "cliente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
