// <auto-generated />
using System;
using Bicicleteria.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bicicleteria.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609193358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bicicleteria.Backend.Models.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Range")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("range");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("carrusel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Mountain Bike Promotion",
                            Range = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Name = "Road Bike Promotion",
                            Range = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Name = "Urban Bike Promotion",
                            Range = 10
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Todas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mountain"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Road"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Urban"
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean")
                        .HasColumnName("availability");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("producto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Availability = true,
                            CategoryId = 1,
                            Description = "26-inch mountain bike with front suspension and disc brakes.",
                            Name = "Mountain Bike 26",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            CategoryId = 2,
                            Description = "Lightweight and fast road bike, ideal for highways. Aluminum frame.",
                            Name = "Road Bike",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            CategoryId = 3,
                            Description = "Comfortable and practical bike for city commuting with front basket.",
                            Name = "Urban Bike",
                            Price = 449.99m
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "admin@bicileteria.com",
                            FirstName = "Admin",
                            LastName = "Sistema",
                            PasswordHash = "$2a$11$KYw7iAZvj87Xi.S5AZJytewQeeg39BssqvS6b8/iyCc1FnGPvoLsO",
                            PhoneNumber = "123456789",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            Email = "client@bicileteria.com",
                            FirstName = "Client",
                            LastName = "Example",
                            PasswordHash = "$2a$11$BXDYkze2IUGuwPSq6aSVn./QN4MjJzqNRoJlC9w9o7yReVM4vUDdK",
                            PhoneNumber = "+34 900 000 002",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            Email = "client@bicileteria.com",
                            FirstName = "Client",
                            LastName = "Example",
                            PasswordHash = "$2a$11$FZSUFJPpi6pV3my7qOAEO.mzhqNNALZQQKRTq62ynh9etpx/OpB.a",
                            PhoneNumber = "+34 900 000 003",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.CarouselItem", b =>
                {
                    b.HasOne("Bicicleteria.Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.Product", b =>
                {
                    b.HasOne("Bicicleteria.Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.User", b =>
                {
                    b.HasOne("Bicicleteria.Backend.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
