// <auto-generated />
using Bicicleteria.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bicicleteria.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bicicleteria.Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Disponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("disponibilidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Bicicleta de montaña de 26 pulgadas con suspensión delantera y frenos de disco.",
                            Disponibilidad = 15,
                            Nombre = "Bicicleta Mountain Bike",
                            Precio = 599.99m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Bicicleta de ruta ligera y rápida, ideal para carreteras. Marco de aluminio.",
                            Disponibilidad = 10,
                            Nombre = "Bicicleta Ruta",
                            Precio = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Bicicleta cómoda y práctica para desplazamientos en ciudad con canasta delantera.",
                            Disponibilidad = 20,
                            Nombre = "Bicicleta Urbana",
                            Precio = 449.99m
                        });
                });

            modelBuilder.Entity("Bicicleteria.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mail");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numerotelefono");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sistema",
                            Mail = "admin@bicileteria.com",
                            Nombre = "Admin",
                            NumeroTelefono = "+34 900 000 001",
                            PasswordHash = "$2a$11$8woRonDE04E3Vwj5JZTPyu4og7luxj5AQ8ds5926KckIZJfmtDQ1a",
                            Tipo = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Vendedor",
                            Mail = "usuario@bicileteria.com",
                            Nombre = "Usuario",
                            NumeroTelefono = "+34 900 000 002",
                            PasswordHash = "$2a$11$mjdC1U/c8fHWAER.31JV9e2MEA6f3LxkFikZ8JL82M2VSWLT6zilC",
                            Tipo = "vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ejemplo",
                            Mail = "cliente@bicileteria.com",
                            Nombre = "Cliente",
                            NumeroTelefono = "+34 900 000 003",
                            PasswordHash = "$2a$11$MJh9C6MWIZrSTPsyyuTxVuX.WROsGVOAdVnnWUnmGlWFdKnRm1J/O",
                            Tipo = "cliente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
