--
-- PostgreSQL database dump
--

\restrict cUXjDeQBjCGtkLrd9hMdHmfwkTpyjjcHwfBj4p2mzPOJAkQGgtDKTKeFkHSTlaa

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-09 16:15:36

SET statement_timeout = 0;
SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16770)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16795)
-- Name: carrusel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carrusel (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    categoryid integer,
    "order" integer DEFAULT 0 CONSTRAINT carrusel_range_not_null NOT NULL
);


ALTER TABLE public.carrusel OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16794)
-- Name: carrusel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carrusel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrusel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16779)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id integer NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16778)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16809)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    price numeric(12,2) NOT NULL,
    imageurl text,
    categoryid integer DEFAULT 0 NOT NULL,
    availability boolean NOT NULL
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16808)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16787)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16786)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16826)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    firstname character varying(100) NOT NULL,
    lastname character varying(100) NOT NULL,
    email character varying(200) NOT NULL,
    phonenumber character varying(20),
    roleid integer NOT NULL,
    passwordhash character varying(500) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16825)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4996 (class 0 OID 16770)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260609193358_InitialCreate	8.0.21
20260621045236_MakeCategoryIdRequired	8.0.21
\.


--
-- TOC entry 5002 (class 0 OID 16795)
-- Dependencies: 225
-- Data for Name: carrusel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carrusel (id, name, categoryid, "order") FROM stdin;
1	Mountain Bike Promotion	2	10
2	Road Bike Promotion	3	10
3	Urban Bike Promotion	4	10
\.


--
-- TOC entry 4998 (class 0 OID 16779)
-- Dependencies: 221
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria (id, name) FROM stdin;
1	Todas
4	Urban
9	Bicicleta
11	Manubrio
12	Anuncios
\.


--
-- TOC entry 5004 (class 0 OID 16809)
-- Dependencies: 227
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (id, name, description, price, imageurl, categoryid, availability) FROM stdin;
34	Venzo	Bicicleta Venzo deportiva, liviana y resistente, ideal para ciudad, paseos y entrenamientos.	95000.00	https://funesbikes.com/wp-content/uploads/2021/02/400001260.png	9	t
31	Viking X	Bicicleta para stunt	80000.00	https://acdn-us.mitiendanube.com/stores/004/567/747/products/ng32ba1fc23-1-bicicleta-vikingx-jump-tuff-25-2026-r26-2ea66101edfd0ffce417691950779019-1024-1024.webp?w=1920	9	t
33	Playera	Bicicleta playera en excelente estado, cómoda, práctica y lista para usar.	24999.00	https://kamikazebikes.com.ar/wp-content/uploads/1678D.jpg	9	t
32	SLP	Bicicleta SLP cómoda, liviana y confiable, ideal para moverte todos los días por la ciudad.	750000.00	https://acdn-us.mitiendanube.com/stores/052/201/products/bip03006-celeste-48cc1189fcd11b48f017404986281661-1024-1024.webp	9	t
35	Bici para niña	Bici linda para que tu hija se divierta	125000.00	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUa0zah3yL9hpHyO5JkQoh0BpMGRzRVNmy8w&s	9	t
\.


--
-- TOC entry 5000 (class 0 OID 16787)
-- Dependencies: 223
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name) FROM stdin;
3	Admin
4	Cliente
\.


--
-- TOC entry 5006 (class 0 OID 16826)
-- Dependencies: 229
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, firstname, lastname, email, phonenumber, roleid, passwordhash) FROM stdin;
5	Alan	Rosales	alan@ejemplo.com	1234567890	4	$2a$11$IgorAgrIthbXTqTnqPVDnuzNEsDbzXM3z35kyfLpm9PeQ4D0YJ55O
6	Tomas	Caussa	admin@example.com	987654321	3	$2a$11$rvQ4/pymOIm2VWaZSY4xRugKEbWkHsR24EiVF.FqJ5uFsjcDsvUzq
3	Client	Example	client@bicileteria.com	+34 900 000 002	4	$2a$11$NOuEl9KJ9xkiIqc8l2X1eOeC1xYwzkUMKn4g6GhT4LI1RbyNlwUaC
4	Client	Example	client@bicileteria.com	+34 900 000 003	4	$2a$11$8zOpjFJGrLa8A37B5HV23OBYLEfdMDrw1sx079Dyeye.zJFaw.5t2
\.


--
-- TOC entry 5012 (class 0 OID 0)
-- Dependencies: 224
-- Name: carrusel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrusel_id_seq', 4, false);


--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 220
-- Name: categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_id_seq', 13, true);


--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 226
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_seq', 41, true);


--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 222
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 5, false);


--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 228
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 6, true);


--
-- TOC entry 4836 (class 2606 OID 16776)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4842 (class 2606 OID 16802)
-- Name: carrusel PK_carrusel; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrusel
    ADD CONSTRAINT "PK_carrusel" PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 16785)
-- Name: categoria PK_categoria; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT "PK_categoria" PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 16819)
-- Name: producto PK_producto; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT "PK_producto" PRIMARY KEY (id);


--
-- TOC entry 4840 (class 2606 OID 16793)
-- Name: roles PK_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT "PK_roles" PRIMARY KEY (id);


--
-- TOC entry 4847 (class 2606 OID 16838)
-- Name: usuarios PK_usuarios; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT "PK_usuarios" PRIMARY KEY (id);


--
-- TOC entry 4845 (class 1259 OID 16846)
-- Name: IX_usuarios_roleid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_usuarios_roleid" ON public.usuarios USING btree (roleid);


--
-- TOC entry 4848 (class 2606 OID 16839)
-- Name: usuarios FK_usuarios_roles_roleid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT "FK_usuarios_roles_roleid" FOREIGN KEY (roleid) REFERENCES public.roles(id) ON DELETE RESTRICT;


-- Completed on 2026-09-09 16:15:37

--
-- PostgreSQL database dump complete
--

\unrestrict cUXjDeQBjCGtkLrd9hMdHmfwkTpyjjcHwfBj4p2mzPOJAkQGgtDKTKeFkHSTlaa

